services:
  booking-engine-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__BookingDb: Host=booking-db;Database=booking;Username=admin;Password=secret;
      ConnectionStrings__AuthDb: Host=auth-db;Database=auth;Username=admin;Password=secret;
    depends_on:
      - booking-db
      - auth-db

  booking-db:
    image: postgres:18
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - booking-db-data-dev:/var/lib/postgresql/18/docker

  auth-db:
    image: postgres:18
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    volumes:
      - auth-db-data-dev:/var/lib/postgresql/18/docker

volumes:
  booking-db-data-dev:
  auth-db-data-dev:
